# Global build settings (apply to all contexts unless overridden)
[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  # Example: Add your Supabase keys here or in Netlify dashboard
  # SUPABASE_URL = "https://your-project.supabase.co"
  # SUPABASE_ANON_KEY = "your-anon-key"
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  TERM = "xterm"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@remix-run/node"]
  directory = "netlify/functions"

# Security headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache control for Remix build assets
[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000"

# Redirect all requests to the Remix Netlify serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# Context-specific settings (optional, customize as needed)
[context.deploy-preview]
  # command = "npm run build:preview"
  # [context.deploy-preview.environment]
  #   SOME_VAR = "preview_value"

[context.production]
  # command = "npm run build:production"
  # [context.production.environment]
  #   NODE_ENV = "production"

[dev]
  command = "remix watch"
  port = 3000


[build]
  publish = "public"
  command = "npm run build"

# Environment variables for local dev go in .env
# For production, set these in the Netlify dashboard, not here!
#[build.environment]
# SUPABASE_URL = ""
# SUPABASE_ANON_KEY = ""

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Permissions-Policy = "interest-cohort=()"

[dev]
  command = "npm run dev"
  port = 3000
