[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm run dev"
  port = 3000

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# Environment variables can be set here or in the Netlify dashboard
[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
    group = "Testing Built Site"
